/**
 * script.js
 *
 * Fetches document data from CONFIG.dataUrl (a local or remote JSON file),
 * groups entries by category, sorts each group newest-first, and renders
 * the result into #app.
 *
 * Also powers the lightweight search bar that filters titles,
 * descriptions, and categories in real time.
 *
 * All user-facing settings live in config.js — do not edit this file
 * unless you are changing behaviour, not configuration.
 */

(function () {
  "use strict";

  /* ── Helpers ────────────────────────────────────────────────────────────── */

  /** Parse "YYYY-MM-DD" into a sortable number (larger = newer). */
  function dateValue(str) {
    return new Date(str).getTime();
  }

  /** Format "YYYY-MM-DD" → "Feb 20, 2026" for display. */
  function formatDate(str) {
    const d = new Date(str + "T00:00:00"); // avoid UTC offset shifting the day
    return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
  }

  /** Escape HTML special characters to prevent XSS. */
  function escHtml(s) {
    return s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  /* ── Data processing ────────────────────────────────────────────────────── */

  /**
   * Group an array of file objects by their `category` field.
   * Returns a Map<string, FileObject[]> preserving insertion order
   * (which we control by sorting the category names alphabetically).
   */
  function groupByCategory(fileList) {
    const map = new Map();

    fileList.forEach((f) => {
      if (!map.has(f.category)) map.set(f.category, []);
      map.get(f.category).push(f);
    });

    // Sort entries within each category: newest first
    map.forEach((entries) => {
      entries.sort((a, b) => dateValue(b.updated) - dateValue(a.updated));
    });

    // Sort category keys alphabetically for a predictable order
    return new Map([...map.entries()].sort((a, b) => a[0].localeCompare(b[0])));
  }

  /* ── Rendering ──────────────────────────────────────────────────────────── */

  /** Returns "file" when the URL points to a downloadable file, else "web". */
  function linkType(url) {
    return /\.(pdf|doc|docx|ppt|pptx|xls|xlsx|zip|txt|csv)(\?.*)?$/i.test(url)
      ? "file"
      : "web";
  }

  const ICON_FILE = `<svg class="card-type-icon" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
    <path d="M3 2h7l3 3v9H3V2z"/>
    <path d="M10 2v3h3"/>
  </svg>`;

  const ICON_WEB = `<svg class="card-type-icon" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
    <circle cx="8" cy="8" r="5.5"/>
    <path d="M8 2.5a8.5 8.5 0 0 1 0 11M8 2.5a8.5 8.5 0 0 0 0 11"/>
    <line x1="2.5" y1="8" x2="13.5" y2="8"/>
  </svg>`;

  /** Render a single entry card as an HTML string. */
  function renderCard(f) {
    const icon = linkType(f.url) === "file" ? ICON_FILE : ICON_WEB;
    return `
      <a
        class="card"
        href="${escHtml(f.url)}"
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Open ${escHtml(f.title)}"
      >
        <div class="card-body">
          <p class="card-title">${escHtml(f.title)}</p>
          <p class="card-desc">${escHtml(f.description)}</p>
        </div>
        <div class="card-meta">
          ${icon}
          <time class="card-date" datetime="${escHtml(f.updated)}">
            ${formatDate(f.updated)}
          </time>
        </div>
      </a>`;
  }

  /** Render a full category section (heading + cards) as an HTML string. */
  function renderCategory(categoryName, entries) {
    const cards = entries.map(renderCard).join("\n");
    return `
      <section class="category" aria-labelledby="cat-${escHtml(categoryName)}">
        <h2 class="category-title" id="cat-${escHtml(categoryName)}">${escHtml(categoryName)}</h2>
        <div class="card-list">
          ${cards}
        </div>
      </section>`;
  }

  /** Write all categories + cards into the #app container. */
  function renderAll(fileList) {
    const app = document.getElementById("app");
    const grouped = groupByCategory(fileList);

    if (grouped.size === 0) {
      app.innerHTML = `<p class="empty-state">No documents found.</p>`;
      return;
    }

    let html = "";
    grouped.forEach((entries, name) => {
      html += renderCategory(name, entries);
    });

    app.innerHTML = html;

    // Stagger-animate each card on initial paint
    requestAnimationFrame(() => {
      const cards = app.querySelectorAll(".card");
      cards.forEach((card, i) => {
        card.style.animationDelay = `${i * CONFIG.cardStaggerMs}ms`;
        card.classList.add("card--visible");
      });
    });
  }

  /* ── Search ─────────────────────────────────────────────────────────────── */

  /**
   * Filter a file list against a lowercase query string.
   * Matches against title, description, and category.
   */
  function filterFiles(fileList, query) {
    if (!query) return fileList;
    const q = query.toLowerCase();
    return fileList.filter(
      (f) =>
        f.title.toLowerCase().includes(q) ||
        f.description.toLowerCase().includes(q) ||
        f.category.toLowerCase().includes(q)
    );
  }

  /** Attach the search input listener. Closes over the full file list. */
  function initSearch(fileList) {
    const input = document.getElementById("search");
    if (!input) return;

    input.addEventListener("input", () => {
      renderAll(filterFiles(fileList, input.value.trim()));
    });
  }

  /* ── Theme ──────────────────────────────────────────────────────────────── */

  /**
   * Apply a theme by setting data-theme on <html>.
   * Pass null to remove the attribute and fall back to the system preference.
   */
  function applyTheme(theme) {
    if (theme === "dark" || theme === "light") {
      document.documentElement.setAttribute("data-theme", theme);
    } else {
      document.documentElement.removeAttribute("data-theme");
    }
  }

  /**
   * Determine the effective (visual) theme right now,
   * considering both the stored preference and the system setting.
   */
  function effectiveTheme() {
    const stored = localStorage.getItem("theme");
    if (stored === "dark" || stored === "light") return stored;
    return window.matchMedia("(prefers-color-scheme: dark)").matches
      ? "dark"
      : "light";
  }

  /** Wire up the toggle button and react to OS-level preference changes. */
  function initTheme() {
    // Apply any previously stored preference immediately
    applyTheme(localStorage.getItem("theme"));

    const btn = document.getElementById("theme-toggle");
    if (!btn) return;

    btn.addEventListener("click", () => {
      const next = effectiveTheme() === "dark" ? "light" : "dark";
      localStorage.setItem("theme", next);
      applyTheme(next);
    });

    // Keep in sync if the OS theme changes while the page is open
    // (only relevant when no manual preference is stored)
    window
      .matchMedia("(prefers-color-scheme: dark)")
      .addEventListener("change", () => {
        if (!localStorage.getItem("theme")) {
          applyTheme(null); // re-evaluate; CSS media query handles the rest
        }
      });
  }

  /* ── Bootstrap ──────────────────────────────────────────────────────────── */

  async function init() {
    initTheme();

    const app = document.getElementById("app");
    app.innerHTML = `<p class="loading-state">Loading documents…</p>`;

    if (location.protocol === "file:") {
      app.innerHTML = `
        <div class="fetch-error">
          <p class="fetch-error__msg">Open via a local server to load data — <code>npx serve .</code></p>
        </div>`;
      return;
    }

    let fileList;
    try {
      const res = await fetch(CONFIG.dataUrl);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      fileList = await res.json();
    } catch (_err) {
      app.innerHTML = `
        <div class="fetch-error">
          <p class="fetch-error__msg">Could not load documents — please try again later.</p>
          <button class="fetch-error__retry" type="button">Retry</button>
        </div>`;
      app.querySelector(".fetch-error__retry").addEventListener("click", init);
      return;
    }

    renderAll(fileList);
    initSearch(fileList);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
